### ISSUE TITLE
Try the BMW Canada API?

### ISSUE THREAD

**Issue by colinbendell** [Alex-Bond/bmw-recall-tool#10]
Fyi, the BMW Canada API appears to be more verbose. Seems to work for other market VINs
`https://crm.bmw.ca/bmwapi/Recalls/XXXXXVINXXXXX?lang=en-ca`

**Comment by Alex-Bond** [comment]
Hey @colinbendell! Can you share any working VIN numbers for this API? None of mine is working there.

**Comment by colinbendell** [comment]
https://crm.bmw.ca/bmwapi/Recalls/WB523CF0XNCJ71557?lang=en-ca

parent page: https://crm.bmw.ca/en-ca/VehicleRecall

**Comment by Hans-O007** [comment]
Not working for me neither. Probably because it's a EU car.
