### ISSUE TITLE
Defect Code 0012890500

### ISSUE THREAD

**Issue by AdrianBinDC** [Alex-Bond/bmw-recall-tool#19]
This code is showing up with `no defect` and it's pre-delivery at the port. According to the BMW Customer Service line, this relates to the following issue:

- Service Action for Program Control Unit DME

According to customer service, this is a software update that can be performed at the dealer.

**Comment by Alex-Bond** [comment]
Can you send me VIN number? You can send it to me@alexbond.info if you don't want to share it publicly.
