### ISSUE TITLE
Error code 52130

### ISSUE THREAD

**Issue by weinschela** [Alex-Bond/bmw-recall-tool#27]
for G70 is seat rail recall

**Comment by weinschela** [comment]
Erroro code 0032470300 is for steering wheel ground connection recall (also G70)

**Comment by Alex-Bond** [comment]
@weinschela thank you for the descriptions. 
First code is just 52130? Can you share example of VIN with it? You can send it to me@alexbond.info if you dont want to publish it here.

**Comment by weinschela** [comment]
To be clear the first one contained 52130.  The EC is longer and already on your site.

**Comment by Alex-Bond** [comment]
@weinschela codes added. thank you!
