### ISSUE TITLE
A Few Code Descriptions

### ISSUE THREAD

**Issue by exon997** [Alex-Bond/bmw-recall-tool#29]
Campaign Number			Description
10011350700			Exhaust gas recirculation cooler customer notification
10011570600			Replacing the exhaust gas recirculation cooler (high temperature)/ Sales Lock
10011150700			Replacing the exhaust gas recirculation cooler (high temperature)/ Sales Lock
10011050700			Replacing exhaust-gas recirculation cooler/ Sales Lock
10011200700			Replacing exhaust gas recirculation cooler/ Sales Lock 
10061050500			Installing the repair cable for the positive battery terminal line/ Sales Lock
10032740200			Reworking steering gear
10061830400			Checking, if required, reworking plug connection of blower controller (Part II)
1STOP024773			F25 N47 - Compliance Examination/ Sales Lock 
10064060200			Optimising the water drain
10013850300			Program control units (DDE)
10013510300			Program control units (DDE)
10032430300			E7x Replace driver's airbag (PSDI-5)/ Sales Lock
10072500200			E7x Replacing front passenger airbag (PSPI-2)

**Comment by Alex-Bond** [comment]
Oh wow!
Big thanks @exon997!
