### ISSUE TITLE
Defect Code Description for Defect Code "0065640300"

### ISSUE THREAD

**Issue by ImDrewToo** [Alex-Bond/bmw-recall-tool#3]
Hi! Awesome tool!!

Here's a defect code I think I know!

Based on my VIN and build, I believe Defect Code "0065640300" comes as an affect from Build Code "6UY" Deletion of Touchscreen

I am told that the line item on my work order is for the car's computer to be reprogrammed to understand that it does not have a touchscreen. So it's a matter of programming (rather than parts) Defect Code. This will be taking place at the VPC (Vehicle Processing Center).

I am a U.S. Market delivery.

More detail on deletion:
https://getjerry.com/insights/bmw-removing-touchscreen-popular-models-chip-shortage

Thanks, 
-Andrew

**Comment by Alex-Bond** [comment]
Hey!

So, one day before you posted the request I added a description for it -`Programming Control Units (CID) Delivery Stop`. And yes - you're right, it's related to the removal of the touchscreen. From what I saw on forums this stop sale requires a mechanic to disable the touchscreen in the actual software as the screen by itself doesn't have touch capabilities anymore.
