### ISSUE TITLE
description for code 0066640100

### ISSUE THREAD

**Issue by cfoote2667** [Alex-Bond/bmw-recall-tool#4]
thank you so much for creating this interface for being able to lookup delays on our cars. it is awesome!

would love to see a description added for code 0066640100 if you are able. thanks!

**Comment by Alex-Bond** [comment]
@cfoote2667 i tried to search descriptions on internet and the only one mention I found here - https://g30.bimmerpost.com/forums/showpost.php?p=28518518&postcount=28
I added it to the list of descriptions, but it's not confirmed.
