### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by ErliPan** [Alex-Bond/bmw-recall-tool#43]
Very useful tool, great job. But currently is giving me error 502. Hope you can fix it soon. Cheers

**Comment by ErliPan** [comment]
Still giving me 502. Example [https://bmw-recall-tool.netlify.app/vin/3MF13DM03P8D36090](https://bmw-recall-tool.netlify.app/vin/3MF13DM03P8D36090)

**Comment by Alex-Bond** [comment]
@ErliPan sorry about that. 2 unrelated issues. Fixed now

**Comment by ErliPan** [comment]
Thank you for the amazing tool. Only issue I think the tool is caching my vin. The bmw site is showing me a new code 0061600800 but yours tool is not showing it... if you could purge the cache for WBY71EG0905Y***** I would be really glad.

**Comment by Alex-Bond** [comment]
> Thank you for the amazing tool. Only issue I think the tool is caching my vin. The bmw site is showing me a new code 0061600800 but yours tool is not showing it... if you could purge the cache for WBY71EG0905Y***** I would be really glad.

My tool doesn't have any cache. It requests every time you refresh the page.
I checked your vin and it showing me 0065760400 issue marked as Closed.

**Comment by ErliPan** [comment]
Ok thanks. I will check again in a few days to see if it shows the new code. Again thank you for the amazing tools. My car is stuck at the dealership and they won't even tell me what the recall is about.
