### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by synrgy350** [Alex-Bond/bmw-recall-tool#9]
Website fails with the following error:

Error while requesting details: Request failed with status code 502

**Comment by Alex-Bond** [comment]
@synrgy350 BMW servers are down since this morning. I'm monitoring availability and as soon as they are back I will virofy tool functionality.
Sorry about that :(

**Comment by Alex-Bond** [comment]
@synrgy350 BMW fixed API and tool is running again

**Comment by synrgy350** [comment]
Thank you Alex!
